#! /usr/bin/perl

use strict;
use warnings;
use File::Temp qw(tempfile);
use File::Basename;
use Cwd qw(abs_path);

# --- Configuration ---
# IMPORTANT: REPLACE THESE WITH YOUR ACTUAL PROJECT DETAILS
my $SOURCE_DIR = "src";             # e.g., "src", "java", "source"
my $TEST_SOURCE_DIR = "test";       # e.g., "test", "src/test/java" (leave empty if none)
my $JAVA_VERSION = "21";            # e.g., "11", "17", "21"

# Your Ant command and target that generates/updates pom.xml
my @ANT_COMMAND = ("ant", "maint.update.dependencies");

# Name of the original pom.xml generated by Ant
my $ORIGINAL_POM_NAME = "pom.xml";

# path to MGIC jars
my $WEB_INF_LIB_PATH = "war/WEB-INF/lib";
my $WEB_INF_CLASSES_PATH = "war/WEB-INF/classes";

my $TOMCAT_LIB_PATH = "c:/tomcat10/lib";

my $MAVEN_TOMCAT_LIB_PROPERTY_NAME = "tomcat.lib.dir";

# --- Script Logic ---

sub run_command {
    my ($cmd_ref, $cwd) = @_;
    print "Executing: @$cmd_ref (in $cwd)\n";
    my $exit_code = system(@$cmd_ref);
    if ($exit_code != 0) {
        my $error_msg = "Command '@$cmd_ref' failed with exit code $exit_code.";
        die $error_msg;
    }
}

sub generate_build_xml_string {
    my $build_xml = "  <build>\n";
    $build_xml .= "    <outputDirectory>\${project.basedir}/$WEB_INF_CLASSES_PATH</outputDirectory>\n";
    $build_xml .= "    <sourceDirectory>\${project.basedir}/$SOURCE_DIR</sourceDirectory>\n";
    if ($TEST_SOURCE_DIR) {
        $build_xml .= "    <testSourceDirectory>\${project.basedir}/$TEST_SOURCE_DIR</testSourceDirectory>\n";
    }
    $build_xml .= "    <plugins>\n";
    $build_xml .= "      <plugin>\n";
    $build_xml .= "        <groupId>org.apache.maven.plugins</groupId>\n";
    $build_xml .= "        <artifactId>maven-compiler-plugin</artifactId>\n";
    $build_xml .= "        <version>3.13.0</version>\n"; # Use a recent version
    $build_xml .= "        <configuration>\n";
    $build_xml .= "          <source>$JAVA_VERSION</source>\n";
    $build_xml .= "          <target>$JAVA_VERSION</target>\n";
    $build_xml .= "        </configuration>\n";
    $build_xml .= "      </plugin>\n";
    $build_xml .= "      <plugin>\n";
    $build_xml .= "        <groupId>org.apache.maven.plugins</groupId>\n";
    $build_xml .= "        <artifactId>maven-dependency-plugin</artifactId>\n";
    $build_xml .= "        <version>3.7.0</version>\n"; # Use a recent version
    $build_xml .= "        <executions>\n";
    $build_xml .= "          <execution>\n";
    $build_xml .= "            <id>analyze-dependencies</id>\n";
    $build_xml .= "            <goals>\n";
    $build_xml .= "              <goal>analyze</goal>\n";
    $build_xml .= "            </goals>\n";
    $build_xml .= "          </execution>\n";
    $build_xml .= "        </executions>\n";
    $build_xml .= "      </plugin>\n";
    $build_xml .= "    </plugins>\n";
    $build_xml .= "  </build>\n";
    return $build_xml;
}

# This function attempts to parse existing dependencies from the POM using regex.
# Highly fragile! Assumes standard XML structure and no comments within dependency blocks.
sub parse_existing_dependencies {
    my ($pom_content) = @_;
    my %declared_gavs; # Store as "groupId:artifactId:version" for lookup

    # Regex to find <dependency> blocks. s flag for dotall.
    while ($pom_content =~ m!<dependency>(.*?)</dependency>!sg) {
        my $dep_block = $1;
        my ($groupId, $artifactId, $version, $scope);

        if ($dep_block =~ m!<groupId>(.*?)</groupId>!s) { $groupId = $1; }
        if ($dep_block =~ m!<artifactId>(.*?)</artifactId>!s) { $artifactId = $1; }
        if ($dep_block =~ m!<version>(.*?)</version>!s) { $version = $1; }
        if ($dep_block =~ m!<scope>(.*?)</scope>!s) { $scope = $1; }

        # Normalize/simplify for comparison
        $groupId //= ''; # Set to empty string if undef
        $artifactId //= '';
        $version //= '';
        $scope //= '';

        # Use a canonical form for comparison, e.g., group:artifact:version
        if ($groupId && $artifactId && $version && $scope) {
            $declared_gavs{"$groupId:$artifactId:$version:$scope"} = 1;
            $declared_gavs{"$artifactId:$version:$scope"} = 1;
        } elsif ($groupId && $artifactId && $version) {
            $declared_gavs{"$groupId:$artifactId:$version"} = 1;
        } elsif ($artifactId && $version) { # Fallback if groupId is missing but artifact/version are there
            $declared_gavs{"$artifactId:$version"} = 1;
        } elsif ($artifactId) { # Even weaker fallback
            $declared_gavs{"$artifactId"} = 1;
        }
    }
    return %declared_gavs;
}

sub normalize_path_for_maven_systempath {
    my ($path_str) = @_;
    my $normalized_path = abs_path($path_str);
    $normalized_path =~ s#\\#/#g;

    if ($^O eq 'msys' && $normalized_path =~ m#^/([a-z])/#i) {
        $normalized_path = uc($1) . ":" . substr($normalized_path, 2);
    }

    $normalized_path;
}

sub get_system_dependencies_xml_string {
    my ($pom_content, $current_project_dir, @lib_dirs_to_scan) = @_;
    my $deps_xml = "";
    my %declared_gavs = parse_existing_dependencies($pom_content);

    foreach my $lib_dir (@lib_dirs_to_scan) {
        my $abs_scan_path;
        if (File::Spec->file_name_is_absolute($lib_dir)) {
            $abs_scan_path = normalize_path_for_maven_systempath($lib_dir);
        } else {
            my $combined_path = File::Spec->catfile($current_project_dir, $lib_dir);
            $abs_scan_path = normalize_path_for_maven_systempath($combined_path);
        }

        if (!-d $abs_scan_path) {
            warn "Warning: '$abs_scan_path' does not exist or is not a directory. Skipping internal JAR detection.\n";
            next;
        }

        print "Scanning '$abs_scan_path' for internal JARs...\n";
        opendir(my $dh, $abs_scan_path) or die "Could not open directory '$abs_scan_path': $!";
        my @files = readdir($dh);
        closedir($dh);

        foreach my $file (@files) {
            next unless $file =~ /\.jar$/i; # Only process .jar files
            next if $file =~ /^\.+$/; # Skip . and ..

            my $jar_full_path = normalize_path_for_maven_systempath(File::Spec->catfile($abs_scan_path, $file));

            my $system_path_value;
            my $jar_filename_only = basename($file);
            # Check if the current scanning path (abs_scan_path) matches the normalized Tomcat lib path
            if ($abs_scan_path eq normalize_path_for_maven_systempath($TOMCAT_LIB_PATH)) {
                my $jar_filename_only = basename($file); # Get just "catalina-tribes.jar"
                $system_path_value = "\$\{$MAVEN_TOMCAT_LIB_PROPERTY_NAME\}/$jar_filename_only";
            } elsif ($abs_scan_path eq normalize_path_for_maven_systempath(File::Spec->catfile($current_project_dir, $WEB_INF_LIB_PATH))) {
                my $jar_filename_only = basename($file); # Get just "catalina-tribes.jar"
                $system_path_value = "\$\{project.basedir\}/$WEB_INF_LIB_PATH/$jar_filename_only";
            } else {
                # For other JARs (e.g., from WEB-INF/lib), use the full absolute path
                $system_path_value = $jar_full_path;
            }

            my $artifact_id_derived = $file;
            $artifact_id_derived =~ s/\.jar$//i; # Remove .jar extension
            
            my $version_derived = "1.0.0-UNKNOWN"; # Default version if not found
            # Attempt to extract version from filename (e.g., my-lib-1.2.3.jar -> 1.2.3)
            if ($artifact_id_derived =~ /-(\d+\.\d+(\.\d+)?([_-][a-zA-Z0-9]+)*)$/i) {
                $version_derived = $1;
                $artifact_id_derived =~ s/-\Q$version_derived\E$//i; # Remove version from artifactId
            } elsif ($artifact_id_derived =~ /-(\d{8}\.\d{6})$/i) { # Handle specific date-based versions like in some snapshots
                 $version_derived = $1;
                 $artifact_id_derived =~ s/-\Q$version_derived\E$//i;
            }

            # Generate a default groupId for internal JARs
            my $group_id_derived = "com.mycompany.internal"; # You can customize this

            # --- Specific rules for common missing libraries (can be extended) ---
            # These override the derived GAV if a known pattern is matched
            if ($file =~ /^jakarta\.jms-api-(\d+\.\d+\.\d+)\.jar$/i) {
                $group_id_derived = "jakarta.jms";
                $artifact_id_derived = "jakarta.jms-api";
                $version_derived = $1;
            } elsif ($file =~ /^com\.ibm\.mq\.jakarta\.jms-(\d+\.\d+\.\d+\.\d+)\.jar$/i) {
                $group_id_derived = "com.ibm.mq"; # Or com.ibm.mq.jakarta
                $artifact_id_derived = "com.ibm.mq.jakarta.jms";
                $version_derived = $1;
            } elsif ($file =~ /^commons-logging-(\d+\.\d+(\.\d+)?)\.jar$/i) {
                $group_id_derived = "commons-logging";
                $artifact_id_derived = "commons-logging";
                $version_derived = $1;
            } elsif ($file =~ /^httpclient-(\d+\.\d+\.\d+)\.jar$/i) {
                $group_id_derived = "org.apache.httpcomponents";
                $artifact_id_derived = "httpclient";
                $version_derived = $1;
            } elsif ($file =~ /^httpcore-(\d+\.\d+\.\d+)\.jar$/i) {
                $group_id_derived = "org.apache.httpcomponents";
                $artifact_id_derived = "httpcore";
                $version_derived = $1;
            }
            # Common Tomcat/JavaEE APIs
            elsif ($file =~ /^(servlet-api|jakarta\.servlet-api)-(\d+\.\d+(?:\.\d+)?)\.jar$/i) {
                $group_id_derived = "jakarta.servlet";
                $artifact_id_derived = "jakarta.servlet-api";
                $version_derived = $2; # Capture version from the matched group
            }
            elsif ($file =~ /^(jsp-api|jakarta\.servlet\.jsp-api)-(\d+\.\d+(?:\.\d+)?)\.jar$/i) {
                $group_id_derived = "jakarta.servlet.jsp";
                $artifact_id_derived = "jakarta.servlet.jsp-api";
                $version_derived = $2;
            }
            elsif ($file =~ /^(jstl|jakarta\.servlet\.jsp\.jstl)-(\d+\.\d+(?:\.\d+)?)\.jar$/i) {
                $group_id_derived = "jakarta.servlet.jsp"; # Or similar for jakarta JSTL
                $artifact_id_derived = "jakarta.servlet.jsp.jstl";
                $version_derived = $2;
            }
           
            # Check if this derived GAV (or a reasonable proxy) is already declared
            my $is_declared = 0;
            foreach my $scope_type (qw(compile provided runtime system test)) {
                if (exists $declared_gavs{"$group_id_derived:$artifact_id_derived:$version_derived:$scope_type"} ||
                    exists $declared_gavs{"$artifact_id_derived:$version_derived:$scope_type"}) {
                    $is_declared = 1;
                    last;
                }
            }
            
            if ($is_declared) {
                print "  Skipping '$file' (already declared in POM with some scope\n";
                next;
            }

            print "  Adding '$file' as a system dependency ($group_id_derived:$artifact_id_derived:$version_derived) from '$abs_scan_path'.\n";
            $deps_xml .= <<EOT;
    <dependency>
      <groupId>$group_id_derived</groupId>
      <artifactId>$artifact_id_derived</artifactId>
      <version>$version_derived</version>
      <scope>system</scope>
      <systemPath>$system_path_value</systemPath>
    </dependency>
EOT
        }
    }
    return $deps_xml;
}

sub main {
    my $current_dir = `pwd`; # Get current working directory
    chomp $current_dir;

    print "Starting dependency analysis process...\n";

    # 1. Run Ant to generate pom.xml
    # eval { run_command(\@ANT_COMMAND, $current_dir); };
    # if ($@) { die "Failed to run Ant build: $@"; }

    # Check if original pom.xml exists
    my $original_pom_path = File::Basename::fileparse($ORIGINAL_POM_NAME);
    if (!-f $original_pom_path) {
        die "Error: Original POM file '$original_pom_path' not found after Ant build. Check your Ant target.\n";
    }

    # Read original POM content for parsing existing dependencies
    my $pom_content;
    {
        local $/ = undef; # Enable slurp mode
        open(my $fh_original, '<', $original_pom_path) or die "Could not open '$original_pom_path' for reading: $!";
        $pom_content = <$fh_original>;
        close $fh_original;
    }
            
    # modify POM content
    my $property_definition = "    <$MAVEN_TOMCAT_LIB_PROPERTY_NAME>$TOMCAT_LIB_PATH</$MAVEN_TOMCAT_LIB_PROPERTY_NAME>\n";
    if ($pom_content !~ m!<properties>.*?</properties>!s) {
        # Properties section does not exist, inject a new one after <modelVersion> or <groupId>
        my $properties_xml = "  <properties>\n$property_definition  </properties>\n";
        if ($pom_content =~ m!(<groupId>.*?</groupId>)!) {
            $pom_content =~ s!(<groupId>.*?</groupId>)!$1\n$properties_xml!s;
            print "Injected new <properties> section with '$MAVEN_TOMCAT_LIB_PROPERTY_NAME'.\n";
        } elsif ($pom_content =~ m!(<modelVersion>.*?</modelVersion>)!) {
            $pom_content =~ s!(<modelVersion>.*?</modelVersion>)!$1\n$properties_xml!s;
            print "Injected new <properties> section with '$MAVEN_TOMCAT_LIB_PROPERTY_NAME'.\n";
        } else {
            warn "Warning: Could not find suitable location to inject <properties> section. '$MAVEN_TOMCAT_LIB_PROPERTY_NAME' property might not be added.\n";
        }
    } else {
        # Properties section exists, check if our property is already there
        if ($pom_content !~ m!<$MAVEN_TOMCAT_LIB_PROPERTY_NAME>.*?</$MAVEN_TOMCAT_LIB_PROPERTY_NAME>!s) {
            # Property not found, add it to the existing <properties> block
            $pom_content =~ s!(</properties>)!$property_definition$1!s;
            print "Added '$MAVEN_TOMCAT_LIB_PROPERTY_NAME' to existing <properties> section.\n";
        } else {
            print "'$MAVEN_TOMCAT_LIB_PROPERTY_NAME' property already present.\n";
            # Optional: Add logic here to update the property's value if it's different from $TOMCAT_LIB_PATH_ABS
        }
    }
    $pom_content =~ s!(<dependency>\s*.*?<scope>)runtime(</scope>\s*</dependency>)!$1compile$2!gs;

    my $system_deps_xml_to_inject = get_system_dependencies_xml_string(
                                        $pom_content,
                                        $current_dir,
                                        $WEB_INF_LIB_PATH,
                                        $TOMCAT_LIB_PATH
                                    );
    if ($system_deps_xml_to_inject) {
        if ($pom_content =~ m#(</dependencies>)#) {
            $pom_content =~ s#(</dependencies>)#$system_deps_xml_to_inject\n$1#;
            print "Injected system dependencies from specified lib paths.\n";
        } else {
            warn "Warning: Could not find </dependencies> tag to inject system dependencies.\n";
            $pom_content =~ s#(</project>)#<dependencies>\n$system_deps_xml_to_inject\n</dependencies>\n$1#;
        }
    }

    my $build_xml_to_inject = generate_build_xml_string();
    if ($pom_content =~ m#(</project>)#) {
        $pom_content =~ s#(</project>)#$build_xml_to_inject\n$1#s;
        print "Injected <build> section\n";
    } else {
        warn "Warning: Could not find </project> to inject <build> section\n";
    }

    my ($fh_temp, $temp_pom_path) = tempfile(
        "pom_modified_XXXX",
        DIR => $current_dir,
        UNLINK => 0, # Don't unlink immediately, we'll do it in finally block
    );
    print $fh_temp $pom_content;
    close $fh_temp;
    print "Modified POM written to '$temp_pom_path'\n";

    print "Running Maven commands...\n";
    eval {
#        run_command(["mvn", "-f", $temp_pom_path, "clean", "install"], $current_dir);
        run_command(["mvn", "-f", $temp_pom_path, "dependency:analyze"], $current_dir);
    };
    if ($@) {
        print "Maven analysis completed with errors: $@\n";
    } else {
        print "Maven analysis completed successfully.\n";
    }

    # 4. Clean up temporary pom.xml
#    print "Cleaning up temporary POM: '$temp_pom_path'...\n";
#    if (unlink $temp_pom_path) {
#        print "Temporary file deleted.\n";
#    } else {
#        warn "Could not delete temporary file '$temp_pom_path': $!\n";
#    }
}

# Execute main function
main();

